#!/bin/bash
git init -qqq
git remote add origin git@github.com:topvalue/m2khaosod_docker.git
git fetch origin -qqq
git checkout origin/main -- compose
mv compose/* ./
mv compose/.vscode ./
rm -rf compose .git
git init
